services:
    frontend:
        build:
            context: ./apps/frontend
            target: development
        ports:
            - "${FRONTEND_PORT}:3000" # dev: 3000, prod: 80
        depends_on:
            - server-comet
            - server-orbit
        restart: unless-stopped
        networks:
            - xrosstalk-net
        develop:
            watch:
                - path: ./apps/frontend/src
                  action: sync
                  target: /usr/local/frontend/src
                - path: ./apps/frontend/package.json
                  action: rebuild

    server-comet:
        build:
            context: ./apps/server-comet
            target: development
        ports:
            - "${COMET_PORT}:5000"
        environment:
            - REDIS_HOST=redis
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
        depends_on:
            - redis
            - rabbitmq
        restart: unless-stopped
        networks:
            - xrosstalk-net
        develop:
            watch:
                - path: ./apps/server-comet/src
                  action: sync
                  target: /usr/local/app/src
                - path: ./apps/server-comet/package.json
                  action: rebuild

    server-orbit:
        build:
            context: ./apps/server-orbit
        ports:
            - "${ORBIT_PORT}:5001"
        environment:
            - REDIS_HOST=redis
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
        depends_on:
            - redis
            - rabbitmq
        restart: unless-stopped
        networks:
            - xrosstalk-net

    redis:
        image: redis:7
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - redis-data:/data
        networks:
            - xrosstalk-net

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "${RABBITMQ_PORT}:5672"
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - xrosstalk-net

volumes:
    redis-data:
    rabbitmq-data:

networks:
    xrosstalk-net:
        driver: bridge
